name: mruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Run Gem Install
      run: gem install rake --no-document
    - name: Add Packages
      run: |
        sudo apt -y install wget build-essential bison git libelf-dev libelf1 libcap2 libbpf-dev
        wget https://github.com/iovisor/bcc/raw/master/libbpf-tools/x86/vmlinux_505.h -O bpf/vmlinux.h
    - name: Run Build
      run: rake