name: mruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Run Gem Install
      run: gem install rake --no-document
    - name: Add Packages
      run: |
        sudo apt -y install wget build-essential bison git libelf-dev libelf1 libcap2
        wget  	http://ftp.br.debian.org/debian/pool/main/l/linux/bpftool_5.10.46-4_amd64.deb -O bpftool_5.10.46-4_amd64.deb
        sudo apt install ./bpftool_5.10.46-4_amd64.deb
    - name: Run Build
      run: rake